common:
  namespace: mysql

mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_USER: "app_user"
    MYSQL_PASSWORD: "1234"

  replicas: 2
  pvc_requests: 2Gi

  image:
    repository: mysql
    version: 8.0

  affinity:
    key: "app"
    operator: "In"
    values: "mysql"
    topologyKey: "kubernetes.io/hostname"

  tolerations:
    key: "app"
    operator: "Equal"
    value: "mysql"
    effect: "NoSchedule"

  resources:
    cpu: 500m
    memory: 1Gi