apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.todoapp.rolingUpdate.maxSurge}}
      maxUnavailable: {{ .Values.todoapp.rolingUpdate.maxUnavailable}}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: secrets-reader
      containers:
      - name: {{ .Values.todoapp.image.name}}
        image: {{ .Values.todoapp.image.repository}}:{{ .Values.todoapp.image.version}}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: app-secrets-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: app-config-volume
          mountPath: "/app/configs"
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.todoapp.resources.requests.memory}}
            cpu: {{ .Values.todoapp.resources.requests.cpu}}
          limits:
            memory: {{ .Values.todoapp.resources.limits.memory}}
            cpu: {{ .Values.todoapp.resources.limits.cpu}}
        env:
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONUNBUFFERED
      {{- range $k, $v := .Values.todoapp.secrets }}
        - name: {{ $k }}
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: {{ $k }}
      {{- end }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-data
      - name: app-secrets-volume
        secret:
          secretName: app-secret
      - name: app-config-volume
        configMap:
          name: app-config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: {{ .Values.todoapp.affinity.weight }}
            preference:
              matchExpressions:
              - key: {{ .Values.todoapp.affinity.key }}
                operator: {{ .Values.todoapp.affinity.operator }}
                values:
                - {{ .Values.todoapp.affinity.values }}
